kbss-cvut/fta-fmea

- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
Fix generation of failure modes during the generation of FTA.
> [Fix kbss-cvut/fta-fmea-ui#45] Fix generation of failure modes

- src/main/java/cz/cvut/kbss/analysis/model/FaultEvent.java
- src/main/java/cz/cvut/kbss/analysis/service/FailureModesTableRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
- Do we presume that every Function and Failure mode will always have assigned a Component (in generation partial FMEA)? Atm Component can be null.
- There can be a case when Failure mode is not assigned to Functions. Do we presume that Failure mode will be always be assigned? In case it wont, do we want to notify user ?
> [Fix kbss-cvut/fta-fmea-ui#46] Fix generation of partial FMEA table 

- src/main/java/cz/cvut/kbss/analysis/FtaApplication.java
- src/main/java/cz/cvut/kbss/analysis/controller/SystemController.java
- src/main/java/cz/cvut/kbss/analysis/dao/BaseDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/GenericDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/RDFDao.java
- src/main/java/cz/cvut/kbss/analysis/model/util/EntityToOwlClassMapper.java
- src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/external/AnnotatorService.java
- calls external convert document service
- stores response into a context named after the imported document in the repository
- imports components from the imported context into the system
@Matthew-Kulich
> implement import-document into system api

- src/main/java/cz/cvut/kbss/analysis/FtaApplication.java
- src/main/java/cz/cvut/kbss/analysis/config/RestConfig.java
- src/main/java/cz/cvut/kbss/analysis/config/conf/AnnotatorConf.java
- src/main/java/cz/cvut/kbss/analysis/controller/AnnotatorController.java
- src/main/java/cz/cvut/kbss/analysis/controller/SystemController.java
- src/main/java/cz/cvut/kbss/analysis/dao/BaseDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/GenericDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/RDFDao.java
- src/main/java/cz/cvut/kbss/analysis/model/Document.java
- src/main/java/cz/cvut/kbss/analysis/model/util/EntityToOwlClassMapper.java
- src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/external/AnnotatorService.java
- src/main/resources/application.yml
> Implement list-documents api

- ontology-generator/ontology/fta-fmea-model.ttl
- src/main/java/cz/cvut/kbss/analysis/FtaApplication.java
- src/main/java/cz/cvut/kbss/analysis/config/RestConfig.java
- src/main/java/cz/cvut/kbss/analysis/config/conf/AnnotatorConf.java
- src/main/java/cz/cvut/kbss/analysis/controller/AnnotatorController.java
- src/main/java/cz/cvut/kbss/analysis/controller/SystemController.java
- src/main/java/cz/cvut/kbss/analysis/dao/BaseDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/GenericDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/RDFDao.java
- src/main/java/cz/cvut/kbss/analysis/model/AbstractEntity.java
- src/main/java/cz/cvut/kbss/analysis/model/Document.java
- src/main/java/cz/cvut/kbss/analysis/model/System.java
- src/main/java/cz/cvut/kbss/analysis/model/util/EntityToOwlClassMapper.java
- src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/external/AnnotatorService.java
- src/main/resources/application.yml
> Extend model to support annotations and documents 

- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultTree.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
Fixes kbss-cvut/fta-fmea-ui#238
**The branch of this PR is based on the branch of PR #75.**
> Fix/fta fmea UI 238 persist fault event scenarios in fault tree context

- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
Fixes kbss-cvut/fta-fmea-ui#237
> [FIX #kbss-cvut/fta-fmea-ui#237] Fix faul tree entity descriptor to allow reading supertypes property

- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
Fixes fault tree entity descriptor.
Related issues kbss-cvut/fta-fmea-ui#237 and kbss-cvut/fta-fmea-ui#238.
> [FIX] Fix fault tree entity descriptor

- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
Partial fix for kbss-cvut/fta-fmea-ui#226
> [FIX kbss-cvut/fta-fmea-ui#226] Read fault tree in transaction to enable lazy loading

- ontology-generator/ontology/fta-fmea-model.ttl
- src/main/java/cz/cvut/kbss/analysis/dao/FaultEventDao.java
- src/main/java/cz/cvut/kbss/analysis/model/AbstractEntity.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultEvent.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
Solving partially 
- kbss-cvut/fta-fmea-ui#245
> Feature/fta fmea UI 219 implement reference nodes

- src/main/java/cz/cvut/kbss/analysis/dao/FaultEventDao.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultEvent.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultEventReference.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
Contributes to 
- kbss-cvut/fta-fmea-ui#245
> [FIX kbss-cvut/fta-fmea-ui#245] Extend FaultEvent.references field to include the fault tree of the referenced fault event

- ontology-generator/ontology/fta-fmea-model.ttl
- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultTree.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultTreeSummary.java
> [Fix #83] Add calculated failure rate, fha based failure rate and failure rate requirement to fault tree summary.

- build.gradle
@blcham 
Contributes to kbss-cvut/fta-fmea-ui#294
> [Fix kbss-cvut/fta-fmea-ui#294] Bump jsonld version to 0.14.3

- ontology-generator/ontology/fta-fmea-model.ttl
- src/main/java/cz/cvut/kbss/analysis/model/FailureRate.java
- src/main/java/cz/cvut/kbss/analysis/model/ava/IndependentSNSItem.java
- src/main/java/cz/cvut/kbss/analysis/model/ava/SNSComponent.java
@blcham 
Contributes to kbss-cvut/fta-fmea-ui#299
> Update jopa model, move stock from reusable component to sns component

- build.gradle
> [Fix #104] Upgrade JOPA

- src/main/java/cz/cvut/kbss/analysis/dao/FaultEventDao.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
@blcham 
Contributes to kbss-cvut/fta-fmea-ui#371
> Create fault tree so that it is attached to FaultTree.system field

- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
@blcham 
Fixes kbss-cvut/fta-fmea-ui#384
> fta-fmea-ui#384 Fix adding new fault event with existing supertype in fault tree diagram

- src/main/java/cz/cvut/kbss/analysis/dao/BaseDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/GenericDao.java
- src/main/java/cz/cvut/kbss/analysis/service/ComplexManagedEntityRepositoryService.java
> #108 Delete context when fault tree or system is deleted context

- src/main/java/cz/cvut/kbss/analysis/dao/FailureModeDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
@blcham 
Fixes #117 
This PR replaces lazy fetch of details with fetching details using native query.
> [Fix #117] Fix fetching fault tree with details

- src/main/java/cz/cvut/kbss/analysis/controller/OperationalDataFilterController.java
> #120 Fix update operational data filter api

- src/main/java/cz/cvut/kbss/analysis/model/FaultEvent.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
@blcham 
Fixes partially kbss-cvut/fta-fmea-ui#399
> Fix updating selected failure rate

- ontology-generator/ontology/fta-fmea-model.ttl
- src/main/java/cz/cvut/kbss/analysis/controller/OperationalDataFilterController.java
- src/main/java/cz/cvut/kbss/analysis/dao/FaultEventTypeDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/ManagedEntityDao.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultEventReference.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultTree.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultTreeSummary.java
- src/main/java/cz/cvut/kbss/analysis/model/Status.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeEvaluationService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeService.java
- src/main/java/cz/cvut/kbss/analysis/service/OperationalDataFilterService.java
- src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#428
> Implement simple fault tree status

- build.gradle
- src/main/java/cz/cvut/kbss/analysis/dao/BaseDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/FaultEventTypeDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/OperationalDataFilterDao.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultEvent.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeService.java
@blcham 
Fix kbss-cvut/fta-fmea-ui#455
This PR also 
- fixes issue caused by solution of updating in correct context 
- bumps jopa version
> Fix/fta fmea UI 455 fix saving triples in default context

- src/main/java/cz/cvut/kbss/analysis/config/conf/OperationalDataConfig.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeEvaluationService.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/external/OperationalDataService.java
- src/main/resources/application.yml
>  evaluate and store fha based failure rate on fault tree evaluation

- src/main/java/cz/cvut/kbss/analysis/config/NoSecurityConfig.java
- src/main/java/cz/cvut/kbss/analysis/config/SecurityConfig.java
> Add no security configuration

- src/main/java/cz/cvut/kbss/analysis/dao/FaultEventTypeDao.java
@blcham 
Fix kbss-cvut/fta-fmea-ui#406
> Filter out FHA with fault tree

- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
> Fix description not saved on update fault event

- src/main/java/cz/cvut/kbss/analysis/controller/util/PagingUtils.java
@LaChope 
Fix sorting of fault tree summaries according to label and snsLabel
> Fix sorting of fault tree summaries according to label and snsLabel

- src/main/java/cz/cvut/kbss/analysis/dao/util/FaultTreeFilterParams.java
@LaChope 
Fixes missing fault tree summaries due to incorrect filtering according to label and snsLabel
> Fix filtering of fault tree summaries according to label and snsLabel

- src/main/java/cz/cvut/kbss/analysis/controller/util/RestExceptionHandler.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultEvent.java
- src/main/java/cz/cvut/kbss/analysis/model/fta/FTAMinimalCutSetEvaluation.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#544
> Improve fault tree evaluation error message when leaf nodes are missing probability

- src/main/java/cz/cvut/kbss/analysis/dao/ManagedEntityDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/SystemDao.java
- src/main/java/cz/cvut/kbss/analysis/dao/UserDao.java
- src/main/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/security/SecurityUtils.java
- src/test/java/cz/cvut/kbss/analysis/dao/FaultEventDaoTest.java
- src/test/java/cz/cvut/kbss/analysis/dao/FaultTreeDaoTest.java
- src/test/java/cz/cvut/kbss/analysis/dao/UserDaoTest.java
- src/test/java/cz/cvut/kbss/analysis/environment/config/TestPersistenceConfig.java
- src/test/java/cz/cvut/kbss/analysis/service/ComponentRepositoryServiceTest.java
- src/test/java/cz/cvut/kbss/analysis/service/FaultEventRepositoryServiceTest.java
- src/test/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryServiceTest.java
- src/test/java/cz/cvut/kbss/analysis/service/SystemRepositoryServiceTest.java
- src/test/java/cz/cvut/kbss/analysis/service/UserRepositoryServiceTest.java
@blcham 
Fixes kbss-cvut/fta-fmea-ui#556
> Fix cant rename or delete system

- src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#574
> Throw exception on system rename if system with the same name exists

- src/main/java/cz/cvut/kbss/analysis/service/security/SecurityUtils.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#581 
Fix problem with fetching current user when logging when and who updated a fault tree.
> Fix creating faultTreeEvents

- src/main/java/cz/cvut/kbss/analysis/service/validation/FaultEventValidator.java
> Remove unique name validation constraint for FaultEvent

- src/main/java/cz/cvut/kbss/analysis/controller/util/RestExceptionHandler.java
- src/main/java/cz/cvut/kbss/analysis/dto/error/ErrorInfo.java
- src/main/java/cz/cvut/kbss/analysis/exception/BadCredentialsException.java
- src/main/java/cz/cvut/kbss/analysis/exception/CalculationException.java
- src/main/java/cz/cvut/kbss/analysis/exception/EntityNotFoundException.java
- src/main/java/cz/cvut/kbss/analysis/exception/LogicViolationException.java
- src/main/java/cz/cvut/kbss/analysis/exception/UsernameNotAvailableException.java
- src/main/java/cz/cvut/kbss/analysis/model/fta/FTAMinimalCutSetEvaluation.java
- src/main/java/cz/cvut/kbss/analysis/security/OntologyAuthenticationProvider.java
- src/main/java/cz/cvut/kbss/analysis/service/SystemRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/UserRepositoryService.java
Resolves partially #kbss-cvut/fta-fmea-ui#550
> Provide messageArguments for exceptions

- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#638
> Fix graph pattern for matching FHA based failure rate

- ontology-generator/ontology/fta-fmea-model.ttl
- src/main/java/cz/cvut/kbss/analysis/dao/FaultTreeDao.java
- src/main/java/cz/cvut/kbss/analysis/model/FaultTreeSummary.java
- src/main/java/cz/cvut/kbss/analysis/model/NamedEntity.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#373
> Add alternative SNS labels

- src/main/java/cz/cvut/kbss/analysis/service/FaultTreeRepositoryService.java
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#659
> Update predicted failure rate on fault tree evaluation

- build.gradle
- src/main/java/cz/cvut/kbss/analysis/config/OpenApiConfig.java
- src/main/java/cz/cvut/kbss/analysis/config/SecurityConfig.java
- src/main/resources/application.properties
- src/main/resources/application.yml
@blcham 
Fix partially kbss-cvut/fta-fmea-ui#668
> Fix/fta fmea UI 668 open api behind proxy

- src/main/java/cz/cvut/kbss/analysis/model/NamedEntity.java
- src/main/java/cz/cvut/kbss/analysis/model/User.java
- src/main/java/cz/cvut/kbss/analysis/service/UserRepositoryService.java
- src/main/java/cz/cvut/kbss/analysis/service/validation/AbstractEntityValidator.java
- src/main/java/cz/cvut/kbss/analysis/service/validation/DefaultEntityValidator.java
- src/main/java/cz/cvut/kbss/analysis/service/validation/NamedEntityValidator.java
- src/main/java/cz/cvut/kbss/analysis/service/validation/UserValidator.java
@blcham 
Fixes kbss-cvut/fta-fmea-ui#673
Set validator supporting User entity in UserRepositoryService
- refactor -  AbstractEntityValidator from NamedEntityValidator
- add UserValidator
> Fix User validation in UserRepositoryService

- Dockerfile
- build.gradle
- ontology-generator/pom.xml
Fixes partially kbss-cvut/fta-fmea-ui#675
Upgrade dependencies.
Partially Tested
`internal` auth
- Login/logout 
- System and fault tree Dashboards - CRUD
- system editor - updating MOH
- fault tree editor - CRUD of fault events
- Combinations of fault tree evaluation and updating fault tree failure rates
> Upgrade java and dependencies
